spring:
    profiles:
        active: dev-test
    jackson:
         serialization-inclusion: NON_EMPTY
    application:
        name: OrganizationService
    cloud:
        consul:
            discovery:
                tags: ${spring.profiles.active}
app:
    key: OrganizationService
    name: 企业管理
    desc: 企业管理
    version: v0.1
    termsOfServiceUrl: 
    contact:
        url:
        name:
        email:
    license:
    licenseUrl:
security:
    basic:
        enabled: true
    ignored: /health,/**/*swagger*,/**/*swagger*/**,/v2/api-docs,/webjars/**
    oauth2:
        client:
            clientId: customer_care_web_server_guj
            clientSecret: 654322
            accessTokenUri: http://dev.jyx365.top/oauth/access_token
            userAuthorizationUri: http://dev.jyx365.top/sso/login
            tokenName: access_token
            #authenticationScheme: query
            #clientAuthenticationScheme: form
            scope: userinfo
        resource:
            userInfoUri: http://dev.jyx365.top/api/v1.0/users/current
server:
    port: 8810
logging:
    level:
        #org.springframework.ldap: DEBUG
        #org.springframework.boot.autoconfigure: DEBUG
        top.jyx365: DEBUG
        #org.springframework.core.env: DEBUG
    file: ./springboot.log
lombok:
    log:
        fieldName: logger
---
#单元测试
spring:
    profiles: dev-int-test 
security:
    oauth2:
        client:
            client-id: customer_care_web_server_guj
            clientSecret: 654322
            accessTokenUri: http://dev.jyx365.top/oauth/access_token
            userAuthorizationUri: http://dev.jyx365.top/sso/login
            tokenName: access_token
            #authenticationScheme: query
            #clientAuthenticationScheme: form
            scope: userinfo
        resource:
            userInfoUri: http://dev.jyx365.top/api/v1.0/users/current
server:
    port: 8710
ldap:
    password: 6Jw8fd7TfnPRd7Gr
    url: ldap://localhost:389
    base: dc=development,dc=jyx365,dc=top
    userDn: cn=Manager,dc=jyx365,dc=top
access_token: bearer etM1tZkFRwDrLzCJrRi74USMcdPWYN
---
spring:
    profiles: dev-prod
security:
    oauth2:
        client:
            client-id: customer_care_web_server_guj
            clientSecret: 654322
            accessTokenUri: http://dev.jyx365.top/oauth/access_token
            userAuthorizationUri: http://dev.jyx365.top/sso/login
            tokenName: access_token
            #authenticationScheme: query
            #clientAuthenticationScheme: form
            scope: userinfo
        resource:
            userInfoUri: http://dev.jyx365.top/api/v1.0/users/current
server:
    port: 8810
ldap:
    password: 6Jw8fd7TfnPRd7Gr
    url: ldap://localhost:389
    base: dc=test,dc=jyx365,dc=top
    userDn: cn=Manager,dc=jyx365,dc=top
---
spring:
    profiles: dev-test
security:
    oauth2:
        client:
            client-id: customer_care_web_server_guj
            clientSecret: 654322
            accessTokenUri: http://dev.jyx365.top/oauth/access_token
            userAuthorizationUri: http://dev.jyx365.top/sso/login
            tokenName: access_token
            #authenticationScheme: query
            #clientAuthenticationScheme: form
            scope: userinfo
        resource:
            userInfoUri: http://dev.jyx365.top/api/v1.0/users/current
server:
    port: 8812
ldap:
    password: 6Jw8fd7TfnPRd7Gr
    url: ldap://localhost:389
    base: dc=test,dc=jyx365,dc=top
    userDn: cn=Manager,dc=jyx365,dc=top
